name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: "Set to true to update snapshots"
        required: false
        default: "false"

permissions:
    contents: write
    
jobs:
  Pull-Docker-Image:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tboronenkodock/app:latest

  Run-Tests:
    runs-on: ubuntu-latest
    needs: Pull-Docker-Image
    steps:
      - name: Pull Docker Image
        run: docker pull tboronenkodock/app:latest

      - name: Run Playwright Tests in Docker Container
        run: |
          docker run --rm \
            -e CI=true \
            tboronenkodock/app:latest \
            bash -c "
              if [ \"$update_snapshots\" == \"true\" ]; then
                echo 'Updating snapshots in CI...';
                npm run pageObjects-chrome -- --update-snapshots;
              else
                echo 'Running tests against existing snapshots...';
                npm run pageObjects-chrome;
              fi
            "

      - name: Upload playwright artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
    
  Commit_Snapshots:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.update_snapshots == 'true' }}
    needs: Run-Tests
    steps:
      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit updates snapshots
        run: |
          git add .
          git commit -m "Update snapshots"

      - name: Push changes
        run: git push origin ${{ github. head_ref }}

    

          